all:

vlaah-python:
	svn export http://svn.mearie.org/snippets/vlaah-python/
	tar czvf "vlaah-python-`echo print VERSION | python -i vlaah-python/vlaah/version.py 2> /dev/null`.tar.gz" vlaah-python
	rm -rf vlaah-python

