#!/bin/bash
REPO=${1:-.}
targets=
while IFS= read src; do
	dest=${src%.txt}.html
	targets="$targets $dest"
	res/processor -b "$REPO" "$src" -o "$dest" -D
done < <(hg -R "$REPO" status -nmac | grep '\.\(en\|ko\|ja\)\.txt$')
echo "TARGETS =$targets"
